-- AlterEnum
ALTER TYPE "QuestionType" ADD VALUE 'SHORT_TEXT';
ALTER TYPE "QuestionType" ADD VALUE 'URL';
ALTER TYPE "QuestionType" ADD VALUE 'EMAIL';
ALTER TYPE "QuestionType" ADD VALUE 'YES_NO';
ALTER TYPE "QuestionType" ADD VALUE 'CUSTOMER_SATISFACTION';
ALTER TYPE "QuestionType" ADD VALUE 'NPS';
ALTER TYPE "QuestionType" ADD VALUE 'CHECKBOX';
ALTER TYPE "QuestionType" ADD VALUE 'RATING';
ALTER TYPE "QuestionType" ADD VALUE 'DATE';
ALTER TYPE "QuestionType" ADD VALUE 'DATE_TIME';
ALTER TYPE "QuestionType" ADD VALUE 'NUMBER';
ALTER TYPE "QuestionType" ADD VALUE 'PERCENTAGE';
ALTER TYPE "QuestionType" ADD VALUE 'SLIDER';
ALTER TYPE "QuestionType" ADD VALUE 'PHONE_NUMBER';
